version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - commitlint
  - composables
  - favicons
  - lintfix
  - nuxt
  - nuxtjs
  - paren
  - pinia
  - popperjs
  - stroustrup
  - stylelint
  - vuejs
ignoreWords: []
import: []
